// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrX5i7C_o9-wSLYJnHXWe1vMi-Ff1GOtw',
    appId: '1:901340579460:android:d5bad33df951d578df64d1',
    messagingSenderId: '901340579460',
    projectId: 'environment-monitoring-s-d169b',
    databaseURL: 'https://environment-monitoring-s-d169b-default-rtdb.firebaseio.com',
    storageBucket: 'environment-monitoring-s-d169b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWeAnC6BFny46Hy6dvmRC-YKBnoT15lU',
    appId: '1:901340579460:ios:845010075215eca5df64d1',
    messagingSenderId: '901340579460',
    projectId: 'environment-monitoring-s-d169b',
    databaseURL: 'https://environment-monitoring-s-d169b-default-rtdb.firebaseio.com',
    storageBucket: 'environment-monitoring-s-d169b.firebasestorage.app',
    iosClientId: '901340579460-2dmp6jfg10jmohhoe1cr2g0m9lbadtba.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
